noske:
  host: http://localhost:10070/bonito/run.cgi
  asynchronous: True
ske:
  api_key: null
  host: https://api.sketchengine.eu/bonito/run.cgi
  username: username
  wait:
    0: 1
    2: 99
    5: 899
    45: null
